//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SingleVenue.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SingleVenue.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to about.
        /// </summary>
        public static string AboutHeaderText {
            get {
                return ResourceManager.GetString("AboutHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add.
        /// </summary>
        public static string AppBarButtonText1 {
            get {
                return ResourceManager.GetString("AppBarButtonText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to calendar.
        /// </summary>
        public static string AppBarButtonTextCalendar {
            get {
                return ResourceManager.GetString("AppBarButtonTextCalendar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to call.
        /// </summary>
        public static string AppBarButtonTextCall {
            get {
                return ResourceManager.GetString("AppBarButtonTextCall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to directions.
        /// </summary>
        public static string AppBarButtonTextDirections {
            get {
                return ResourceManager.GetString("AppBarButtonTextDirections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to share.
        /// </summary>
        public static string AppBarButtonTextShare {
            get {
                return ResourceManager.GetString("AppBarButtonTextShare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu Item.
        /// </summary>
        public static string AppBarMenuItemText1 {
            get {
                return ResourceManager.GetString("AppBarMenuItemText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MY APPLICATION.
        /// </summary>
        public static string ApplicationTitle1 {
            get {
                return ResourceManager.GetString("ApplicationTitle1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to venue.
        /// </summary>
        public static string AppNameLower {
            get {
                return ResourceManager.GetString("AppNameLower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VENUE.
        /// </summary>
        public static string AppNameUpper {
            get {
                return ResourceManager.GetString("AppNameUpper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dining at.
        /// </summary>
        public static string DiningAt {
            get {
                return ResourceManager.GetString("DiningAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hours.
        /// </summary>
        public static string HoursHeaderText {
            get {
                return ResourceManager.GetString("HoursHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to location.
        /// </summary>
        public static string LocationHeaderText {
            get {
                return ResourceManager.GetString("LocationHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to menu.
        /// </summary>
        public static string MenuHeaderText {
            get {
                return ResourceManager.GetString("MenuHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to menus.
        /// </summary>
        public static string MenusHeaderText {
            get {
                return ResourceManager.GetString("MenusHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeftToRight.
        /// </summary>
        public static string ResourceFlowDirection {
            get {
                return ResourceManager.GetString("ResourceFlowDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en-US.
        /// </summary>
        public static string ResourceLanguage {
            get {
                return ResourceManager.GetString("ResourceLanguage", resourceCulture);
            }
        }
    }
}
